### PR TITLE
# Kata Containers 1.4.2

### PR DESCRIPTION
**Pull request by bergwolf**
Version bump no changes

### CODE REVIEW

**Comment by caoruidong** [comment]
lgtm

**Comment by jodh-intel** [comment]
lgtm

**Comment by jodh-intel** [comment]
CI's are all failing. It looks like they are trying to checkout a `stable-1.4` packaging branch... which doesn't exist:

```
Cloning github.com/kata-containers/packaging
package github.com/kata-containers/packaging: no Go files in /tmp/jenkins/workspace/kata-containers-proxy-ubuntu-16-04-PR/go/src/github.com/kata-containers/packaging
/tmp/jenkins/workspace/kata-containers-proxy-ubuntu-16-04-PR/go/src/github.com/kata-containers/packaging /tmp/jenkins/workspace/kata-containers-proxy-ubuntu-16-04-PR/go/src/github.com/kata-containers/proxy
Checking out to stable-1.4
error: pathspec 'stable-1.4' did not match any file(s) known to git.
```

/cc @chavafg, @jcvenegas.

**Comment by jodh-intel** [comment]
Hmm, is this related to https://github.com/kata-containers/tests/pull/1033 I wonder?

/rebuild

**Comment by chavafg** [comment]
https://github.com/kata-containers/tests/pull/1035 should solve this issue.

**Comment by bergwolf** [comment]
osx build and metrics are failing but they are not affected by the PR anyway.

**Pull request merged**
