### PR TITLE
Ignore .swp file

### PR DESCRIPTION
**Pull request by liyingjun**
.swp file should be ignored

### CODE REVIEW

**Comment by jodh-intel** [comment]
Thanks for raising! Travis is failing as you need to change your commit slightly as all commits need a summary line (containing a subsystem prefix) and a body (see https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format).

So, you could change your commit to something like this:

```
git: Ignore editor swap files

Updated `.gitignore` to ignore swap files created by editors.

Fixes #41.

Signed-off-by: liyingjun liyingjun1988@gmail.com
```

By the way, if you wanted to, you could raise similar PRs for the other components.

Also, if you're using `vim`:

```
$ cat <<EOT | tee -a ~/.vimrc
" location of swap files
:set dir=>/tmp
EOT
```

**Comment by gnawux** [comment]
-1

I think you may configure a global git ignore configuration in your local host for the IDE/editor related files.

There are many different Editor/IDEs, and many of them have there own temp files or meta files. These could be covered by local configuration instead of inserting ignore file in every project.

**Comment by jodh-intel** [comment]
Yep - I agree with @gnawux.

@liyingjun - are you happy for this PR to be closed?

**Comment by liyingjun** [comment]
OK, fair enough

**Pull request closed without merging**
