### PR TITLE
# Kata Containers 1.0.1

### PR DESCRIPTION
**Pull request by jcvenegas**
Version bump no changes

### CODE REVIEW

**Comment by jodh-intel** [comment]
We use [semver](https://semver.org/) meaning `1.0.1` is a bugfix version. That can be true for proxy+shim as they are nops. We also apply the same version number to all Kata components.

But the runtime and the agent are not bugfix versions - we know that we've made incompatible changes to the runtime+agent: the latest runtime does **not** work with the `1.0.0` packaged agent in the `1.0.0` image (https://github.com/kata-containers/packaging/tree/master/obs-packaging/kata-containers-image).

Hence, strictly according to semver rules, our next release should be `2.0.0` I believe.

We have been relatively relaxed about the *type* of semver version we've assigned in the past, but we are going to have to be more rigid from now on imho given things like the [pending security vulnerability disclosure process](https://github.com/kata-containers/community/pull/39).

/cc @grahamwhaley, @egernst, @sboeuf, @kata-containers/architecture-committee.

**Comment by grahamwhaley** [comment]
Much that leaping to a 2.x.x hurts me a little, I can only agree that we need to have this formal and followed - and, given we had that recent agent update that was not backwards compatible (the 'ephemeral' issue) - then either:
- we need to be more careful and formalise our backwards compatibility
- or we are going to have some pretty rapid major version bumps coming I predict.

Good point @jodh-intel . First discussion to have might be how we feel about backwards compatibility?

**Comment by jodh-intel** [comment]
@gnawux, @bergwolf - any comment on the version number issue above?

**Comment by bergwolf** [comment]
@jodh-intel I think we should define "backward compatibility" first. If we want to make sure new runtime can always talk to old agent, I'm afraid any agent protocol change will break the backward compatibility, since the runtime will be using the new field that old agent does not understand.

OTOH, if by "backward compatible", we only ensure that old runtime can still talk to new agent, the `ephemeral` change does not break the backward compatibility, and most of the agent protocol change won't break it either unless some field is removed from the agent protocol.

**Pull request closed without merging**
