### PR TITLE
CI: Fire a test PR for the jenkins CI (Do not merge)

### LINKED ISSUE #57: Test issue - ignore
Moo :cow:

### PR DESCRIPTION
**Pull request by nitkon**
Make a minor readme change to fire a test
PR for IBM Power Jenkins CI.

Fixes #57

Signed-off-by: Nitesh Konkar <niteshkonkar@in.ibm.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
Hey, @nitkon - presuming you didn't add the documentation team as a specific review group to this PR, then this is *great* - github used the recently merged `CODEOWNERS` file to auto-request the docs team it loks ;-)
/cc @ttx @fungi

**Comment by nitkon** [comment]
@jodh-intel : Yup. I did not add any review group. I have raised another PR as I deleted the fork from which I had submitted this PR.

**Comment by grahamwhaley** [comment]
@nitkon - I'm confused - why did you close this and delete the branch?
If it was because a review group got automatically added - that is *meant to happen* - it is part of our 'replace pullapprove' strategy. You modified a document, so the document reviewers automatically got added as a 'required to review' group :-)

**Comment by nitkon** [comment]
@grahamwhaley: Actually I deleted my branch by mistake & that's why I had to close this PR.

**Pull request closed without merging**
