### PR TITLE
Ignore the coverage files

### LINKED ISSUE #39: Update .gitignore to ignore coverage artifacts
Currently when we run `make test` we get coverage.txt file which we need to ignore.

### PR DESCRIPTION
**Pull request by coolsvap**
Fixes #39

Signed-off-by: Swapnil Kulkarni <me@coolsvap.net>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Hi @coolsvap - thanks for raising! However, we actually have an "in flight" change in PR #33 which will negate the need for this PR.

What I suggest is that we wait until #33 lands, and you can then rework this PR to ignore `profile.cov` and `coverage.html`. Let me chase the team to see if we can get #33 landed...

**Comment by coolsvap** [comment]
@jodh-intel sure.

**Comment by jodh-intel** [comment]
Hi @coolsvap - #33 has now landed so you could rework this to ignore the files mentioned above.

**Comment by coolsvap** [comment]
@jodh-intel I updated .gitignore to ignore the files profile.cov and coverage.html.

**Comment by jodh-intel** [comment]
Thanks @coolsvap.

lgtm

**Comment by jodh-intel** [comment]
ping @kata-containers/proxy.

**Comment by bergwolf** [comment]
lgtm, Thanks!

**Pull request merged**
