### PR TITLE
Add minimal contribution guidelines

### LINKED ISSUE #13: Add Contribution Guidelines
The project needs to have a basic contribution guidelines.

### PR DESCRIPTION
**Pull request by ydjainopensource**
Fixes #13

Signed-off-by: Yash Jain <ydjainopensource@gmail.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
Hi @ydjainopensource - I see you are updating commits to fix the CI problems - I don't know why it failed the Signed-off (unless your commit email was different from your SoB email maybe). But, you will also need a subject 'prefix: ' on your commit(s). I see the Travis checkcommits tool picking that up.

**Comment by jodh-intel** [comment]
Hi @ydjainopensource - thanks for doing this.

I'm sorry to be "picky", but could you make this even simpler? As I mentioned on https://github.com/kata-containers/community/issues/5, I think that all the minimal `CONTRIBUTING.md` files need to be as brief as possible [*]. Literally just:

```
For details on how to contribute to the Kata Containers project, please see the main [contributing document](https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md).
```

I appreciate it's helpful to put the contact details in each one too. However, we're trying really hard to centralise as much as possible after learning a few lessons with https://github.com/clearcontainers. It's hard to keep multiple similar documents current and correct (make that "almost impossible" :).

So, by making these minimal files as brief as possible, we ensure, as far as possible, that they won't change. But we can of course update the single "real" `CONTRIBUTING.md` as often as we need to, to ensure it contains as much useful information as possible.

---
[*] -  Well, we *could* just stick a URL in each file, but I feel that's taking it a bit far ;)

**Comment by ydjainopensource** [comment]
Hi @jodh-intel 

I have removed the contact details.

**Comment by jodh-intel** [comment]
Thanks @ydjainopensource!

lgtm

@klynnrif, @rcaballeromx  - could you take a look please?

**Comment by rcaballeromx** [comment]
LGTM

**Comment by sameo** [comment]
LGTM

**Pull request merged**
