### PR TITLE
proxy: this is a test - DNM

### PR DESCRIPTION
**Pull request by chavafg**
do not run tests or merge this.

Fixes #11111.

Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
Heh, I went chasing why the metrics CI had failed some builds @chavafg - I guess the 'depends' in this PR is what is causing the issues. I will ignore ;-)

**Comment by chavafg** [comment]
@grahamwhaley thanks, should be solved now that https://github.com/kata-containers/tests/pull/799 is merged. I have re-kicked the job just to see how it goes now.

**Comment by chavafg** [comment]
recheck

**Comment by chavafg** [comment]
recheck

**Pull request closed without merging**
