### PR TITLE
Contributing Guidelines

### LINKED ISSUE #13: Add Contribution Guidelines
The project needs to have a basic contribution guidelines.

### PR DESCRIPTION
**Pull request by ydjainopensource**
I have added contribution guidelines.....simply merged the guidelines from Clear containers and RunV repo.....I have also included few changes in the readme to point to the license and contact info.

Fixes #13

### CODE REVIEW

**Comment by jodh-intel** [comment]
Reviewers please see https://github.com/kata-containers/proxy/pull/14#issuecomment-353188215.

**Comment by gnawux** [comment]
Agree with the [comment by @jodh-intel](https://github.com/kata-containers/proxy/pull/14#issuecomment-353188215). We should have a single place to put these guidelines.

**Comment by caoruidong** [comment]
Just like @jodh-intel said in https://github.com/kata-containers/community/issues/5, now we can create a minimal CONTRIBUTING.md in these repos.

**Comment by jodh-intel** [comment]
Hi @ydjainopensource - do you want to rework to create the minimal `CONTRIBUTING.md` file for the proxy repo (and/or any of the others by the way :) ?

**Comment by ydjainopensource** [comment]
Sure I will send a PR soon.

**Comment by jodh-intel** [comment]
@ydjainopensource - thanks!

**Pull request closed without merging**
