### PR TITLE
backport: 1.6.2 backport patches

### PR DESCRIPTION
**Pull request by ganeshmaharaj**
Backport includes below changes.

https://github.com/kata-containers/proxy/pull/172
https://github.com/kata-containers/proxy/pull/169
https://github.com/kata-containers/proxy/pull/155

### CODE REVIEW

**Comment by jcvenegas** [comment]
I see quite a lot linter issues.

**Comment by ganeshmaharaj** [comment]
@jodh-intel i cherry-picked them using `git cherry-pick -x -m1 <merge SHA>` which will get the full delta of the PR if it the PR had multiple commits. I should have stuck to the document. i would be more than happy to re-work the patches if that is more preferrable.

**Comment by grahamwhaley** [comment]
I know a number of upstream (kernel) maintainers have scripts they use to help automate the backporting. I wonder if any of those are available and suitable (or adaptable)...

**Pull request merged**
