### PR TITLE
# Kata Containers 1.2.0

### PR DESCRIPTION
**Pull request by jcvenegas**
- logging: Fix incorrect logger usage
- logging: Redirect yamux warnings/errors to logger
- proxy: close yamux session properly
- proxy: Maintain communication state with a heartbeat
- logging: Add sandbox CLI option
- logging: Use WithError() for all errors

7fd3734 logging: Fix incorrect logger usage
ec252d8 logging: Redirect yamux warnings/errors to logger
1fbb8b3 proxy: wait copy goroutine to quit
22c6f40 proxy: close yamux session properly
063d58f proxy: Maintain communication state with a heartbeat
1672418 logging: Add sandbox CLI option
9b6bb05 logging: Display standard announce message
246f707 CI: Update bash on Travis OSX for hashes
73dbb10 logger: Die if unable to create syslog hook
0cfa402 main: Exit on fatal error
7681a94 logging: Use WithError() for all errors

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm

**Comment by devimc** [comment]
lgtm

**Comment by grahamwhaley** [comment]
travis (OSX), ARM (not active yet) and Zuul CIs I can live without/explain.
the openstack/third-party-check - is that something we can ignore right now @jcvenegas @chavafg - istr some chat that it was temporarily broken, but I've not been tracking that discussion...

**Comment by chavafg** [comment]
we can ignore zuul check for now, merging :)

**Pull request merged**
