### PR TITLE
Test commit for testing Zuul CI

### PR DESCRIPTION
**Pull request by cboylan**
Working on getting Zuul CI running for kata. Lets see what happens.

Depends-On: https://review.openstack.org/602628

### CODE REVIEW

**Comment by sboeuf** [comment]
recheck

**Comment by chavafg** [comment]
recheck

**Comment by jodh-intel** [comment]
Hi @cboylan - could you give a brief update on where we are wrt getting zuul working?

**Comment by cboylan** [comment]
@jodh-intel We've got the Ubuntu Xenial job running and failing on Zuul in the same manner that it fails under Jenkins. @chavafg is working to debug those failures. I just pushed https://review.openstack.org/577563 to add fedora support and am checking really quickly now that I haven't regressed Ubuntu (via the updated depends on in the first commit on this PR).

Rough plan that @chavafg and @sboeuf and I came up with was to get Ubuntu, Centos, and Fedora jobs running then have Zuul talk to the runtime repo as that gets more PRs. Use that to gather feedback and if Kata is happy with it the next step will be to deploy a Kata tenant within our Zuul deployment and use Zuul properly with configs living directly in the Kata repo(s).

**Comment by cboylan** [comment]
recheck

**Comment by cboylan** [comment]
recheck

**Comment by cboylan** [comment]
recheck

**Comment by jodh-intel** [comment]
Hi @cboylan - thanks for the update - sounds good to me.

**Comment by cboylan** [comment]
recheck

**Comment by chavafg** [comment]
recheck

**Comment by cboylan** [comment]
recheck

**Comment by cboylan** [comment]
recheck

**Comment by cboylan** [comment]
recheck

**Comment by cboylan** [comment]
recheck

**Comment by cboylan** [comment]
recheck

**Comment by chavafg** [comment]
recheck

**Comment by cboylan** [comment]
recheck

**Comment by cboylan** [comment]
recheck

**Comment by cboylan** [comment]
recheck

**Comment by cboylan** [comment]
recheck

**Comment by cboylan** [comment]
recheck

**Comment by cboylan** [comment]
recheck

**Comment by chavafg** [comment]
recheck

**Comment by chavafg** [comment]
recheck

**Comment by cboylan** [comment]
recheck

**Comment by sboeuf** [comment]
@cboylan Seems to work :) (fedora28 needs to be fixed but at least we have Ubuntu !)
Let us know when runtime and tests repo will be ready ;)

**Comment by cboylan** [comment]
recheck

**Comment by cboylan** [comment]
recheck

**Comment by cboylan** [comment]
recheck

**Comment by cboylan** [comment]
recheck

**Comment by chavafg** [comment]
recheck

**Comment by cboylan** [comment]
recheck

**Comment by jodh-intel** [comment]
Still seeing lots of zuul failures @cboylan. I assume this is still down to https://github.com/kata-containers/tests/issues/418.

**Comment by grahamwhaley** [comment]
Weekly checkup on Zuul then - @cboylan @chavafg , now we figured out the 'cannot start new VM' issues from last week, is Zuul looking pretty stable.
iirc - do we still have F28 work to do on Zuul?
Main Issue for tracking Zuul progress I guess is over at https://github.com/kata-containers/ci/issues/42

**Comment by chavafg** [comment]
Fedora 28 still not working. The main issue is that most of the time the VMs get hanged when running the tests[1], but there is also instability when running the docker integration tests iirc.

Anyway, the last error was from building qemu, which haven't seen before.

```
  CC      util/event_notifier-posix.o
  CC      util/mmap-alloc.o
  CC      util/oslib-posix.o
  CC      util/qemu-openpty.o
  CC      util/qemu-thread-posix.o
  CC      util/memfd.o
  CC      util/envlist.o
util/memfd.c:40:12: error: static declaration of ‘memfd_create’ follows non-static declaration
 static int memfd_create(const char *name, unsigned int flags)
            ^~~~~~~~~~~~
In file included from /usr/include/bits/mman-linux.h:115,
                 from /usr/include/bits/mman.h:45,
                 from /usr/include/sys/mman.h:41,
                 from /home/zuul/src/github.com/kata-containers/qemu/include/sysemu/os-posix.h:29,
                 from /home/zuul/src/github.com/kata-containers/qemu/include/qemu/osdep.h:104,
                 from util/memfd.c:28:
/usr/include/bits/mman-shared.h:46:5: note: previous declaration of ‘memfd_create’ was here
 int memfd_create (const char *__name, unsigned int __flags) __THROW;
     ^~~~~~~~~~~~
make: *** [/home/zuul/src/github.com/kata-containers/qemu/rules.mak:66: util/memfd.o] Error 1
make: *** Waiting for unfinished jobs....
```
@devimc @jcvenegas any idea? ^^^

[1] - https://github.com/kata-containers/tests/issues/418

**Comment by devimc** [comment]
seems like you need this patch https://github.com/kata-containers/packaging/blob/master/obs-packaging/qemu-lite/patches/0001-memfd-fix-configure-test.patch

**Comment by raravena80** [comment]
Ping @cboylan any updates? Thx

**Comment by cboylan** [comment]
recheck

**Comment by mnaser** [comment]
recheck

**Comment by raravena80** [comment]
@cboylan ping, can we close this? or this needs to be open indefinitely? Thx!

**Comment by chavafg** [comment]
recheck

**Comment by caoruidong** [comment]
Does it work now?

**Comment by chavafg** [comment]
recheck

**Comment by raravena80** [comment]
@cboylan @chavafg @caoruidong ping (from your weekly Kata herder) any status?

**Comment by jodh-intel** [comment]
@cboylan, @mnaser - Any update on this? Shall we just close this now maybe?

**Comment by mnaser** [comment]
@jodh-intel 

I'm not sure.  I think this is a good ticket to track Zuul progress.. how can we get Kata up and running in Zuul?

**Comment by jodh-intel** [comment]
We probably need @cboylan and @chavafg to weigh in here, but I was under the impression the problem was still the Ubuntu kernel crash. The last I heard, we were waiting for folk to test the latest upstream kernel with Xenial. Did that happen does anyone know?

But now bionic is out, is the situation any better I wonder? I know that the Ubuntu kernel team were keen to help us, but they do need us to run those upstream kernels under the vexxhost environment so they can rule out the Ubuntu kernel changes I believe.

**Comment by mnaser** [comment]
@jodh-intel We don't run Ubuntu for our hypervisors so we wouldn't really be able to do that :)

**Comment by jodh-intel** [comment]
@mnaser, @chavafg - have you tried bionic and f29? If they still crash in the same way, we're kinda stuck. But it would definitely be worth raising kernel bugs for those to versions on launchpad and bugzilla respectively.

Bottom line: how can we progress this to even attempt to evaluate zuul folks?

**Comment by mnaser** [comment]
@jodh-intel I unfortunately don't have the resources/time to invest into trying to make this work at the moment :(

I can give some help pointing out to next steps / directions.

**Comment by grahamwhaley** [comment]
iirc, for the problem of nesting newer kernels/distros on older hosts, we had a link to a backport patch that may fix it (the link came from RH folks iirc). afaik, we never got to try that patch on a host to see if that was the solution.
I can dig up details if we need a link to the thread and the patch link.

**Comment by mnaser** [comment]
It's hard for us to change host kernels.. also long term for any potential deployers/users of Kata, it would be beneficial to not have to run a custom kernel on the host to make Kata work

**Comment by grahamwhaley** [comment]
If we are talking about the same thing, then see:
https://github.com/kata-containers/tests/issues/418
and in particulary the post https://github.com/kata-containers/tests/issues/418#issuecomment-406377060
that points to a kernel patch for the 'L0 kernel' - it is a KVM patch.
Thus, I think that would have to be applied to the host kernels. TBH, it feels like something you'd want to backport if you wanted to support virtualisation of future guests.

**Comment by chavafg** [comment]
I also think this is on host kernel side and not only a kata-related issue. For example, on Azure or GCE, we do not have this issue.

**Comment by mnaser** [comment]
We're running the latest CentOS kernel at the moment.

**Comment by chavafg** [comment]
fedora28 re-enabled on zuul, lets check how it goes.

**Comment by chavafg** [comment]
recheck

**Comment by jodh-intel** [comment]
```
2018-12-14 17:29:53.510366 | ubuntu-xenial | No resources found.
2018-12-14 17:29:54.262926 | ubuntu-xenial | clusterrole.rbac.authorization.k8s.io/flannel created
2018-12-14 17:29:54.270795 | ubuntu-xenial | clusterrolebinding.rbac.authorization.k8s.io/flannel created
2018-12-14 17:29:54.280029 | ubuntu-xenial | serviceaccount/flannel created
2018-12-14 17:29:54.291657 | ubuntu-xenial | configmap/kube-flannel-cfg created
2018-12-14 17:29:54.313604 | ubuntu-xenial | daemonset.extensions/kube-flannel-ds-amd64 created
2018-12-14 17:29:54.323592 | ubuntu-xenial | daemonset.extensions/kube-flannel-ds-arm64 created
2018-12-14 17:29:54.335979 | ubuntu-xenial | daemonset.extensions/kube-flannel-ds-arm created
2018-12-14 17:29:54.347658 | ubuntu-xenial | daemonset.extensions/kube-flannel-ds-ppc64le created
2018-12-14 17:29:54.367242 | ubuntu-xenial | daemonset.extensions/kube-flannel-ds-s390x created
2018-12-14 17:29:54.507418 | ubuntu-xenial | No resources found.
2018-12-14 17:29:59.628138 | ubuntu-xenial | No resources found.
2018-12-14 17:30:04.740628 | ubuntu-xenial | No resources found.
2018-12-14 17:31:57.214712 | ubuntu-xenial | Makefile:69: recipe for target 'kubernetes' failed
2018-12-14 17:31:57.214862 | ubuntu-xenial | make: *** [kubernetes] Error 1
2018-12-14 17:31:57.627153 | ubuntu-xenial | ERROR
2018-12-14 17:31:57.627643 | ubuntu-xenial | {
2018-12-14 17:31:57.627764 | ubuntu-xenial |   "delta": "0:47:06.939642",
2018-12-14 17:31:57.627875 | ubuntu-xenial |   "end": "2018-12-14 17:31:57.217665",
2018-12-14 17:31:57.627983 | ubuntu-xenial |   "msg": "non-zero return code",
2018-12-14 17:31:57.628101 | ubuntu-xenial |   "rc": 2,
2018-12-14 17:31:57.628205 | ubuntu-xenial |   "start": "2018-12-14 16:44:50.278023"
2018-12-14 17:31:57.628313 | ubuntu-xenial | }
```

**Comment by chavafg** [comment]
Fedora job failed because `fdisk` is not found in the `PATH`:
```
[91m[1m• Failure [0.075 seconds][0m
docker volume
[90m/home/zuul/src/github.com/kata-containers/tests/integration/docker/volume_test.go:18[0m
  passing a block device
  [90m/home/zuul/src/github.com/kata-containers/tests/integration/docker/volume_test.go:122[0m
    [91m[1mshould be mounted [It][0m
    [90m/home/zuul/src/github.com/kata-containers/tests/integration/docker/volume_test.go:123[0m

    [91mExpected error:
        <*errors.errorString | 0xc420092430>: {
            s: "bash: fdisk: command not found\n",
        }
        bash: fdisk: command not found
        
```
Seems like zuul machines do not include `/usr/sbin` in the `PATH`.
I have opened https://review.openstack.org/#/c/625679/ to fix the issue.

**Comment by chavafg** [comment]
recheck

**Comment by jodh-intel** [comment]
Any further progress on this on @cboylan, @mnaser?

**Comment by grahamwhaley** [comment]
tbh, the next most likely step for kata and Zuul is for me to try and get the metrics CI jobs running on Zuul. I'm not going to get to that in the next couple of weeks though I suspect.
Until we have a permanent stable Zuul CI implementation, or if we decided to drop the notion, then I think this PR will just sit here as a test case...

**Comment by chavafg** [comment]
for QA CI, the fedora job is fixed, but still need to check why the ubuntu job fails... I'll try to make some time this week for that.

**Comment by grahamwhaley** [comment]
recheck

as SoB/DCO merge has landed in Zuul configs: https://review.openstack.org/#/c/630998/

**Comment by grahamwhaley** [comment]
recheck

**Comment by grahamwhaley** [comment]
@ttx @fungi

Well, looks like the zuul DCO test is enabled and working - above we can see the `SUCCESS` status for `dco-license` in the Zuul comment (the test commit does have a Signed-off-by in it).
If we follow the link to the logs, the Ansible-ish logs look a touch confusing, as there is a 'fail' task that is predicated on the DCO check failing - so what you get in the logs is a second element which is basically 'the fail failed', meaning it passed ;-) The key word there is 'skipped'.

From [the logs](http://logs.openstack.org/74/74/a77fc6b82dab0368f1cdc4d4d39ef6390c7a9526/third-party-check/dco-license/2566318/job-output.txt.gz#_2019-01-18_20_56_09_752436):

```
2019-01-18 20:56:09.752436 | TASK [validate-dco-license : Developer Certificate of Origin (DCO) license check]
2019-01-18 20:56:10.426418 | localhost | ok: Runtime: 0:00:00.015914
2019-01-18 20:56:10.471529 | 
2019-01-18 20:56:10.471753 | TASK [validate-dco-license : License check failed]
2019-01-18 20:56:10.541009 | localhost | skipping: Conditional result was False
```

**Comment by fungi** [comment]
Agreed, while I recommend the ara-report interface there for browsing the task breakdown more conveniently than attempting to parse the stream log, the logic in the validate-dco-license role is pretty confusing. I'm not sure why it has two tasks and breaks the actual failure logic into a separate one from the commit message parsing, but I might be missing a subtle problem which makes it necessary. @pabelanger can hopefully explain the reasoning behind that.

**Comment by pabelanger** [comment]
The reason for the double task, is if validate-dco-license : Developer Certificate of Origin actually fails --sign-off check, we don't error, we because the shell code actually worked.  So, we register the results and use the next task with the fail task to format somewhat of an error message. The key here is failed_when: > 1. We can change this, but the idea was if > 1, when we likely have an issue with the git commands.

So yes, we skip the failed here, because result != 0

**Comment by fungi** [comment]
@pabelanger: Thanks. So the reason the `validate-dco-license : Developer Certificate of Origin` doesn't explicitly perform an `exit 1` or similar instead of setting `result=1` is to avoid masking other errors which might result from running `git show`?

**Comment by pabelanger** [comment]
Yah, basically. I am not opposed to change it, this was v1 for ansible-network worked.  If we remove it, and that task fails, we won't be able to display any failure message. So there is trade offs.

**Comment by ttx** [comment]
Agree the resulting logs are quite confusing... just so that you can differentiate an unlikely git show error. At the very least we should change that "License check failed" title into something more explicit...

**Comment by grahamwhaley** [comment]
/zuul-recheck
as I'd quite like to see the WIP check pick up the label on this one :-)

**Comment by ttx** [comment]
Oh actually the /zuul-recheck does only trigger SoB rechecking, not WIP (which can be retriggered by unlabeling/labeling). We could change that though.

**Comment by grahamwhaley** [comment]
yeah, indeed. Right now I think that is OK/correct - the WIP should only need to re-check if a label changes or the PR is updated (and hence the subject line may have changed). Let's see how it goes - it is easy to apply the recheck logic later to WIP if we need to.

**Comment by grahamwhaley** [comment]
/zuul-recheck
with https://review.openstack.org/#/c/641086/ landed, hopefully we have a Zuul CI job tied back to the proxy repo again, which we can then build upon. Let's see if it fires.....

**Comment by jodh-intel** [comment]
@cboylan, @grahamwhaley, @ttx - this PR has been open for 328 days. *Please* can we close it now? :)

**Comment by grahamwhaley** [comment]
@jodh-intel - I looked at this earlier and contemplated the same. It was used back in March, but also has a 'friend' in #154 which also serves a very similar purpose.
We can probably close this one. let's get at least one ack from either @ttx or @cboylan ... or at least give them a chance ;-)

**Comment by jodh-intel** [comment]
Sorry, I don't understand why we need two PRs for the same thing...? Also, why is this taking so long? Could someone summarise the situation to avoid having to read the entirety of these two PRs?

**Comment by grahamwhaley** [comment]
The PRs have handled between them three different cycles of testing the Zuul intergration for Kata:
1) this PR for the original Zuul integration
2) this PR was then used for the WIP/SOB stuff as well when we deprecated pullapprove
3) the other PR was opened by me as I needed some subtle differences in what it was checking, and I do not own this PR so could not modify it.

As I say, yes, we can probably close this one, but should give the owners a chance to respond.

**Comment by cboylan** [comment]
No objection from me to close this. The zuul integration has evolved and largely moved on from this PR.

**Comment by grahamwhaley** [comment]
Thanks @cboylan , and for your on-going support on working out Zuul. Closing now...

**Pull request closed without merging**
