### PR TITLE
CI: Enable centralised static checks

### LINKED ISSUE #16: Enable checkcommits
Enable [checkcommits](https://github.com/clearcontainers/tests/tree/master/cmd/checkcommits) which will requires that all PRs have:

- a `Signed-off-by:` line.
- a `Fixes #XXX` comment where `XXX` is a github issue number.
- Requires all commits to have a "sub-system" followed by a colon, followed by a brief description.
- Requires a blank line after the subsystem.
- Requires all commits to have a fuller description after the sub-system that will contain the `Fixes ###` and `Signed-off-by:` comments.

### PR DESCRIPTION
**Pull request by jodh-intel**
Run the static checks defined in the tests repository. Currently, this
just runs the `checkcommits` tool that requires all PRs to contain a
"Fixes #XXX" comment and a "Signed-off-by:" comment.

Fixes #16.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Replaces #17.

**Comment by grahamwhaley** [comment]
@jodh-intel I think you hit the travis thing again :-(

**Comment by jodh-intel** [comment]
Indeed I have. I'll try again, but do feel we **really** need to move off Travis asap ;((

**Comment by jodh-intel** [comment]
... and Travis has failed again ;(((((((((

**Pull request closed without merging**
