### PR TITLE
Fix the url of the Kata Containers architecture documentation

### PR DESCRIPTION
**Pull request by lujinda**
The old url, return 404 when accessing

### CODE REVIEW

**Comment by lifupan** [comment]
Hi, @lujinda Please open an defect for this issue and then add a "Fixes" label  into your commit log.
You can have a reference on https://github.com/kata-containers/proxy/commit/10c6d5aa57d1307e0b58acf47fe15dc095f6951b

**Comment by lujinda** [comment]
> Hi, @lujinda Please open a defect for this issue and then add a "Fixes" label into your commit log.
> You can have a reference on [10c6d5a](https://github.com/kata-containers/proxy/commit/10c6d5aa57d1307e0b58acf47fe15dc095f6951b)

Sorry, I have modified it。

**Comment by devimc** [comment]
@lujinda please take a look to these commit examples https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#examples

**Comment by egernst** [comment]
Ah, that was my fault @lujinda  -- thanks for opening.  Couple things you'll want to do:
* update commit header: "docs: fix kata arch doc url"
* Make sure there is a space between the commit header and body of message (in this case, your Fixes: #xxxx).
* Add a signed-off by (git commit --amend -s, git push -f ....)

Thanks for the contribution!

**Comment by egernst** [comment]
@lujinda - I updated your "fixes" to point to an issue instead of a Pull request.  Interesting that travis was okay with this.  FYI @jodh-intel 

Change looks good to me - can anyone else PTAL?

**Pull request merged**
