### PR TITLE
# Kata Containers 1.9.0-alpha1

### PR DESCRIPTION
**Pull request by katabuilder**
- ci: Allow travis to use go install script

3a5319f ci: Allow travis to use go install script

### CODE REVIEW

**Comment by egernst** [comment]
It looks like we need some help with the vendoring on the proxy repository. @chavafg @GabyCT - can either of you PTAL so we can move forward with release?

```
# Gopkg.lock is out of sync:
github.com/hashicorp/yamux: imported or required, but missing from Gopkg.lock's input-imports
github.com/sirupsen/logrus: imported or required, but missing from Gopkg.lock's input-imports
github.com/sirupsen/logrus/hooks/syslog: imported or required, but missing from Gopkg.lock's input-imports
github.com/stretchr/testify/assert: imported or required, but missing from Gopkg.lock's input-imports
github.com/davecgh/go-spew: prune options changed ( -> NUT)
github.com/davecgh/go-spew: no hash digest in lock
github.com/hashicorp/yamux: prune options changed ( -> NUT)
github.com/hashicorp/yamux: no hash digest in lock
github.com/pmezard/go-difflib: prune options changed ( -> NUT)
github.com/pmezard/go-difflib: no hash digest in lock
github.com/sirupsen/logrus: prune options changed ( -> NUT)
github.com/sirupsen/logrus: no hash digest in lock
github.com/stretchr/testify: prune options changed ( -> NUT)
github.com/stretchr/testify: no hash digest in lock
golang.org/x/crypto: prune options changed ( -> NUT)
golang.org/x/crypto: no hash digest in lock
golang.org/x/sys: prune options changed ( -> NUT)
golang.org/x/sys: no hash digest in lock
# vendor is out of sync:
github.com/davecgh/go-spew: no digest in Gopkg.lock to compare against hash of vendored tree
github.com/hashicorp/yamux: no digest in Gopkg.lock to compare against hash of vendored tree
github.com/pmezard/go-difflib: no digest in Gopkg.lock to compare against hash of vendored tree
github.com/sirupsen/logrus: no digest in Gopkg.lock to compare against hash of vendored tree
github.com/stretchr/testify: no digest in Gopkg.lock to compare against hash of vendored tree
golang.org/x/crypto: no digest in Gopkg.lock to compare against hash of vendored tree
golang.org/x/sys: no digest in Gopkg.lock to compare against hash of vendored tree
The command ".ci/static-checks.sh" failed and exited with 1 during .
```

**Comment by egernst** [comment]
@jodh-intel can you fix this one, too?

**Comment by chavafg** [comment]
@egernst, this was fixed on #212, restarted the travis job.

**Comment by jodh-intel** [comment]
Restarted the metrics CI.

**Comment by jodh-intel** [comment]
The metrics CI is failing due to the following fwics:

```
15:18:50 docker: Error response from daemon: OCI runtime create failed: Cannot find usable config file (config file "/etc/kata-containers/configuration.toml" unresolvable: file /etc/kata-containers/configuration.toml does not exist, config file "/usr/share/defaults/kata-containers/configuration.toml" unresolvable: file /usr/share/defaults/kata-containers/configuration.toml does not exist): unknown.
```

**Comment by chavafg** [comment]
@jodh-intel this was because as we are not changing code, it should skip the whole CI. Fixed the job configuration and now it passed.

**Comment by jodh-intel** [comment]
Thanks @chavafg.

**Pull request merged**
