### PR TITLE
CI: add setup.sh and run.sh to execute integration tests

### PR DESCRIPTION
**Pull request by chavafg**
.ci/setup.sh will setup the environment with
latest changes to be able to execute Kata Containers.

.ci/run.sh will execute the integration tests that live
in the 'kata-containers/tests' repository.

Fixes: #55.

Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
LGTM

**Comment by jodh-intel** [comment]
lgtm

**Comment by jodh-intel** [comment]
CI is failing as all PRs are still blocked on #54...

**Comment by laijs** [comment]
#56 & #54 depends on each other on the test, I just merged #54.

**Comment by chavafg** [comment]
rebased this PR with latest changes, now all checks should pass.

**Pull request merged**
