### PR TITLE
CI: Fire a test PR for jenkins CI (Do not merge)

### LINKED ISSUE #57: Test issue - ignore
Moo :cow:

### PR DESCRIPTION
**Pull request by nitkon**
Fire a test PR for IBM Power Jenkins CI

Fixes #57

Signed-off-by: Nitesh Konkar <niteshkonkar@in.ibm.com>

### CODE REVIEW

**Comment by nitkon** [comment]
CI fails on Power because of vCPU hotplug [issue](https://github.com/kata-containers/runtime/issues/1155). 
docker test suite fails
```
23:00:08 Ran 223 of 234 Specs in 1892.762 seconds
23:00:08 FAIL! -- 181 Passed | 42 Failed | 0 Pending | 11 Skipped --- FAIL: TestIntegration (1919.27s)
23:00:08 FAIL
```

**Comment by grahamwhaley** [comment]
/test
/me hijacks @nitkon PR to do a test build for s390x ;-)

**Comment by grahamwhaley** [comment]
hijacking @nitkon PR again, this time to test pullapprove. @nitkon - let me know if this is interfering with your work, and I'll open a new PR...
/cc @ttx 
/test

**Comment by grahamwhaley** [comment]
oh, in fact, maybe we need a real PR change - I'll also flip a DNM label on/off

**Comment by ttx** [comment]
/zuul-recheck -- we should now see the new user-friendly links in the check details

**Comment by nitkon** [comment]
`jenkins-ci-Power8-ubuntu-16-04-initrd` is now green where we test 3 test buckets: functional, docker and docker-compose. cc @grahamwhaley

**Comment by grahamwhaley** [comment]
Yay @nitkon - indeed, the Power8 CI build looks good - with the pleasing end result of:

```
17:20:15 Ran 213 of 234 Specs in 1880.413 seconds
17:20:15 SUCCESS! -- 213 Passed | 0 Failed | 0 Pending | 21 Skipped PASS
```

:-)
I think we are nearly ready to enable on other repos - just two things I think we should try...
 - I just merged your 'cleanup' script PR, so we should ensure that works
 - and I think we should ensure that, and the rest of the CI, works .... twice in a row. Just to make sure we don't get any 'lingering effects' between builds.

To that end, I'm going to re-trigger a full CI build here, and then we can expect to do that again...
What I'm trying to avoid is enabling a new CI on the busy repos (runtime, tests), as then if we do have any niggles you get put in the 'critical path' ;-)

**Comment by nitkon** [comment]
@grahamwhaley : The CI failed on Power.
```
17:58:13 Summarizing 1 Failure:
17:58:13 
17:58:13 [Fail] logs logs with docker check logs functionality [It] should work 
17:58:13 /home/jenkins/workspace/kata-containers-proxy-Power8-16.04-PR-initrd/go/src/github.com/kata-containers/tests/integration/docker/logs_test.go:30
17:58:13 
17:58:13 Ran 214 of 234 Specs in 1882.933 seconds
17:58:13 FAIL! -- 213 Passed | 1 Failed | 0 Pending | 20 Skipped --- FAIL: TestIntegration (2393.72s)
17:58:13 FAIL
```

**Comment by grahamwhaley** [comment]
Oh, interesting fail @nitkon given that it worked on the previous run, and I believe you have been running that by hand locally... so, I guess you'll need to run it in a loop locally and check if we have an instability?
That is not a test I think I've seen fail on any other system btw, for reference.

**Comment by nitkon** [comment]
@grahamwhaley: Works fine locally on the system. Let's re-nudge the CI again?

**Comment by nitkon** [comment]
@grahamwhaley: I tried it 6 times locally in a loop. The CI passes that test now but fails to clean up the system.
```
21:34:43 Ran 214 of 234 Specs in 1886.406 seconds
21:34:43 SUCCESS! -- 214 Passed | 0 Failed | 0 Pending | 20 Skipped PASS
21:34:43 
21:34:43 Ginkgo ran 1 suite in 40m6.048808247s
21:34:43 Test Suite Passed
21:34:43 bash sanity/check_sanity.sh
21:34:44 ERROR: 4 pods left and found at /var/lib/vc/sbs
21:34:44 make: *** [Makefile:51: docker] Error 1
21:34:44 Build step 'Execute shell' marked build as failure
21:34:44 Performing Post build task...
21:34:44 Match found for :.* : True
21:34:44 Logical operation result is TRUE
21:34:44 Running script  : #!/bin/bash
```

**Comment by grahamwhaley** [comment]
OOh, leaky pods :-) That might be a sign of something more insidious... that check is basically saying 'after we cleaned up all the containers I can still see some kata related container stuff sat on the disk that should not be there'. That may or may not be arch specific. I would suspect not arch specific myself.
@sameo saw something similar earlier today - did you figure out what it was @sameo , or did it just 'go away' ?

**Comment by nitkon** [comment]
So the `leaky pods` issue seems to persist.  ` ERROR: 2 pods left and found at /var/lib/vc/sbs`
This seems because we are [not cleaning up](https://github.com/kata-containers/runtime/blob/1d79338a1a1a9cd526b4d350731fa24df11cef22/virtcontainers/qemu.go#L669) `ConfigStoragePath` when there is a [qmp/qemu failure](https://github.com/kata-containers/tests/issues/1157#issuecomment-464610446).

Should we cleanup `ConfigStoragePath` in our [cleanupVM](https://github.com/kata-containers/runtime/blob/1d79338a1a1a9cd526b4d350731fa24df11cef22/virtcontainers/qemu.go#L666) function as well. 
@sboeuf @grahamwhaley @jodh-intel @bergwolf

**Comment by nitkon** [comment]
Update: The Power CI Is failing due to leaky pods issue. These issues are being tracked here:
1. https://github.com/kata-containers/tests/issues/1157
2. https://github.com/kata-containers/runtime/pull/1267

**Comment by nitkon** [comment]
/retest
Last 5 manual retests have been successful, triggering once more...

**Comment by nitkon** [comment]
@grahamwhaley: Should we configure other repos CI to run on Power8 machine as well now?

**Comment by grahamwhaley** [comment]
@nitkon - if you are confident they will pass, and/or you are willing to leap on any issues with gusto :-), then sure. I know you found a runtime repo unit test that failed for power8 yesterday for instance?
You could hand-try the runtime and tests repos (or all the code repos - agent, proxy, shim) if you wanted locally first to avoid any surprises.
Given we know some things might turn up, I'd suggest we enable one at a time. The runtime repo is probably the most challenging - so, I'd say we tackle that one... first (and get it over with ;-) ).
If you want us to enable the runtime repo for power8, just say here, and I or @chavafg will do that for you, np.

**Comment by nitkon** [comment]
@grahamwhaley : Lets start with agent, proxy, shim, osbuilder repos first ;-)  Could you enable it for P8...

**Comment by grahamwhaley** [comment]
OK, I've added power8 jobs for agent/shim/osbuilder - we already had proxy :-)
@chavafg - hopefully I got the clone/edit cycles right ;-) I shall note something then - I think this is sort of the first *other* job we have added for osbuilder outside of a single x86_64 ubuntu build. It is probably the right thing to do (having one osbuilder job per arch) - but, @nitkon - do we use osbuilder for power8?

**Comment by grahamwhaley** [comment]
An update, so @chavafg @GabyCT know I had to make some changes....

my initial power8 jobs were failing - turns out it is because a bunch of our jenkins jobs git clone the tests repo into $HOME, which never gets cleaned up on a bare metal machine (does not matter on the one shot cloud instances of coures), and then causes a 'tests dir already exists' error early on in the whole jenkins build kickoff. I prefer to clone (ideally I'd `go get`, but that would need golang installed by default on all slaves) into the final $WORKSPACE/GOPATH itself, which then gets cleaned up later... for a new clean workspace dir for the next build.

Here is what I have set now:

```bash
#!/bin/bash

# As we have set the shell to /bin/bash, we need to reset -e (and let's set -x as well eh)
set -ex

# These vars are required by the .ci scripts in the repos
export ghprbPullId
export ghprbTargetBranch
export AGENT_INIT=yes TEST_INITRD=yes OSBUILDER_DISTRO=fedora

export REPO_NAME="github.com/kata-containers/proxy"
export TESTS_REPO_NAME="github.com/kata-containers/tests"
export TESTS_GIT_NAME="https://github.com/kata-containers/tests.git"
export GOPATH="${WORKSPACE}/go"

# Dump our env to aid initial debug
echo "Our ENV looks like:"
env

#go get -d -u ${TESTS_REPO_NAME}
git clone ${TESTS_GIT_NAME} ${GOPATH}/src/${TESTS_REPO_NAME}
cd ${GOPATH}/src/${TESTS_REPO_NAME}

.ci/jenkins_job_build.sh "${REPO_NAME}"
```

and here is what we had before
```
#!/bin/bash

set -e

export ghprbPullId
export ghprbTargetBranch

export AGENT_INIT=yes TEST_INITRD=yes OSBUILDER_DISTRO=alpine

cd $HOME
git clone https://github.com/kata-containers/tests.git
cd tests

.ci/jenkins_job_build.sh "github.com/kata-containers/agent"
```

I'd propose we try to place everything related to a jenkins job build under the jenkins `$WORKSPACE` if we can, which then means 'clean workspace before build' will do what we expect.

**Comment by chavafg** [comment]
Hi @grahamwhaley, agree with the changes... I think that there are some jobs that still do the clone on `$HOME`, will try to look at them later today and change them.

**Comment by grahamwhaley** [comment]
Hey @nitkon - what's your plan with the Power CI machine? - gonna try and work out why it has got a bit grumpy, or just start by giving it a reboot and then see if it persists??

**Comment by nitkon** [comment]
Currently Kata CI is failing because of https://github.com/kata-containers/tests/blob/1267d819a5f749a8ffa892aade3e304eea4d727e/.ci/setup_env_ubuntu.sh#L50
@jcvenegas @chavafg 
However libostree-dev can be installed on ppc64le despite the error from the above code: 
`gpg: no valid OpenPGP data found.`
```
 sudo chronic sudo -E add-apt-repository ppa:alexlarsson/flatpak -y
Failed to add key.
gpg: keybox '/tmp/tmpx7omc5mf/pubring.gpg' created
gpg: /tmp/tmpx7omc5mf/trustdb.gpg: trustdb created
gpg: key C793BFA2FA577F07: public key "Launchpad PPA for Alexander Larsson" imported
gpg: Total number processed: 1
gpg:               imported: 1
Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: no valid OpenPGP data found.
jenkins@kata1:~$ chronic sudo -E apt install -y libostree-dev
jenkins@kata1:~$
```

**Comment by nitkon** [comment]
Power CI fails with:
```
23:26:14 ~/workspace/kata-containers-proxy-Power8-16.04-PR-initrd/go/src/github.com/qemu/qemu ~/workspace/kata-containers-proxy-Power8-16.04-PR-initrd/go/src/github.com/kata-containers/tests

23:26:15 error: The following untracked working tree files would be overwritten by checkout:
23:26:15 	slirp/COPYRIGHT
23:26:15 Please move or remove them before you can switch branches.
23:26:15 Aborting
23:26:15 Build step 'Execute shell' marked build as failure
23:26:15 Performing Post build task...
23:26:15 Match found for :.* : True
23:26:15 Logical operation result is TRUE
23:26:15 Running script  : #!/bin/bash
23:26:15 export GOPATH=$WORKSPACE/go
23:26:15 export GOROOT="/usr/local/go"
23:26:15 export PATH=${GOPATH}/bin:/usr/local/go/bin:/usr/sbin:/usr/local/bin:${PATH}
23:26:15 
23:26:15 cd $GOPATH/src/github.com/kata-containers/tests
23:26:15 .ci/teardown.sh "$WORKSPACE/artifacts"
```
@chavafg : This error seems to be similar to the one seen earlier on ARM CI.

**Comment by grahamwhaley** [comment]
@chavafg @nitkon I have a couple of thoughts on what could cause this sort of error:
1. Jenkins job setup - might not be purging the build tree between runs, so leaving some not-easy-to-clean git cruft around
1. maybe something in our merge/depends branch setup code is not handling dirty trees or we have some sort of merge clash there

**Comment by nitkon** [comment]
@grahamwhaley @jodh-intel : I deleted the workspace directory on the CI machine and re-ran the CI. However, the CI failed due to the same issue.

**Comment by chavafg** [comment]
this also started to fail on arm. Taking the look at the code, the only place where I see that this might be failing in Power is:
https://github.com/kata-containers/tests/blob/master/.ci/ppc64le/lib_install_qemu_ppc64le.sh#L59
and in the case of arm in:
https://github.com/kata-containers/tests/blob/master/.ci/aarch64/lib_install_qemu_aarch64.sh#L61-L62

/cc @Pennyzct

**Comment by Pennyzct** [comment]
Hi~ @chavafg I have tried to fix the ARM CI break down with this new [PR#1541](https://github.com/kata-containers/tests/pull/1541), ptal. ;)

**Comment by nitkon** [comment]
The qemu build failure was due to gcc version 8.0+  installed on the system. I had to move to gcc 5.0+ version to successfully compile qemu stable 2.11. This issue was not seen on qemu master branch.

I guess qemu vanilla version will get updated soon once this PR gets merged https://github.com/kata-containers/runtime/pull/1407. @chavafg

**Comment by nitkon** [comment]
Power-CI Power CI is green!

**Comment by amshinde** [comment]
@nitkon Do you need this test PR anymore?

**Comment by caoruidong** [comment]
Can we close it？ ping @nitkon

**Comment by nitkon** [comment]
yes. good to close.

**Pull request closed without merging**
