### PR TITLE
CI: trigger build on s390x jenkins CI

### LINKED ISSUE #144: To trigger the CI - ignore
/test

### PR DESCRIPTION
**Pull request by tuan-hoang1**
Fixes #144

Signed-off-by: Tuan Hoang <tmhoang@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
/test

let's give it a build nudge. @tuan-hoang1 - we may need to join you to the kata github org so you can do that. Once we have one build though I believe you should be able to trigger further jenkins rebuilds for s390x directly through the jenkins master UI.

**Comment by jcvenegas** [comment]
This is just a test PR right?  adding do not merge label

**Comment by jodh-intel** [comment]
Hi @tuan-hoang1 - any update on this?

**Comment by tuan-hoang1** [comment]
Current stress test fails due to timeout of IO ops like disk or network or something. Has nothing to do with Kata nor s390x. Trying again later ...

**Comment by jodh-intel** [comment]
Hi @tuan-hoang1 - any update on this testing?

**Comment by tuan-hoang1** [comment]
Hi sorry, I couldn't find the time. Will do next week.

**Comment by tuan-hoang1** [comment]
We need this https://github.com/kata-containers/runtime/pull/1449 to fix current Build #41.

**Comment by tuan-hoang1** [comment]
We need this https://github.com/kata-containers/packaging/pull/422 to fix current Build 45 : http://jenkins.katacontainers.io/job/kata-containers-proxy-s390x-18.04-PR-initrd/45/consoleFull

**Comment by alicefr** [comment]
We also need this PR https://github.com/kata-containers/runtime/pull/1460

**Comment by alicefr** [comment]
Wit those changes our internal CI is working

**Comment by tuan-hoang1** [comment]
Thanks for the detailed explanation.
Last delay was due to a new CPU hotplug introduced from a Power commit which took us a while to figure out because we thought we fixed it (apparently not). We also reached a quite stable build series in our internal CI, which hopefully improves official Kata builds. We did not have this status last month.

**Comment by grahamwhaley** [comment]
How are we doing @tuan-hoang1 ? - looking at the slave build log, I see a lot of good builds, but the occasional failure.  Still some wrinkles to iron out?

**Comment by tuan-hoang1** [comment]
@grahamwhaley , we are still as solid as iron.
46, 47 are successful.
48 is unknown to me.
49, 50 are my fault :D triggered the wrong parameter.
51 is good.
52 says the build was "restart". I don't know what happened.
53,54 are ok.
55 is sprinting.

**Comment by grahamwhaley** [comment]
48 was a test fail, but it could be spurious:

```bash
11:49:20 Summarizing 1 Failure:
11:49:20 
11:49:20 [Fail] [Serial Test] Hot plug CPUs with a parent cgroup [It] should not fail with parent cgroup: ////systemd 
11:49:20 /home/jenkins/workspace/kata-containers-proxy-s390x-18.04-PR-initrd/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:212
11:49:20 
11:49:20 Ran 12 of 247 Specs in 201.933 seconds
11:49:20 FAIL! -- 11 Passed | 1 Failed | 0 Pending | 235 Skipped --- FAIL: TestIntegration (201.95s)
11:49:20 FAIL
```

So, at this point I suggest - when you are happy that we enable the CI on either the tests or the runtime repo (they are the two most active), as long as @chavafg agrees - and then we see how it goes.
We can also start by **not** making it a 'required' CI.

**Comment by tuan-hoang1** [comment]
Understood, and agree with your points. So I think if we all agree, we could start enabling runtime next week.
@alicefr has been working tirelessly with our internal CI to make runtime working.

**Comment by alicefr** [comment]
We're hitting another gofmt complain for `virtcontainers/qem_s390x.go`. I let our CI run and if it's successful, I'll open a PR

**Comment by tuan-hoang1** [comment]
The last 2 failures 56, 57 are from 1.5.4 and 1.6.2 branches. I guess we don't backport anything for s390x, so the failures are expected.

**Comment by tuan-hoang1** [comment]
Friendly ping @grahamwhaley.
Since we don't backport s390x changes to 1.6.x and older, would you mind adding a check in the official s390x jenkin script for 'proxy' ? And also for later projects we are going to add soon (runtime, etc.). Not sure if it is a job on your side on our side, I'm happy to help, please let me know.
On the other hand, was the gofmt complaint in `virtcontainers/qem_s390x.go` fixed in `kata-containers/runtime/pull/1460`, @alicefr  ? If yes, we are ready to add runtime for s390x CI.

**Comment by grahamwhaley** [comment]
@tuan-hoang1 - ah, you'd like us to disable the S390 CI for stable branches? That is possible in Jenkins, yes.
@chavafg - how about we enable @tuan-hoang1 and @alicefr to have some admin rights on the Jenkins master, so we can share some ownership across architectures and timezones? Anybody object? I think we should discuss some 'ground rules' maybe, as if you accidentally break the master (it has happened once before), then all CI stops !! ;-)

**Comment by grahamwhaley** [comment]
I know @alicefr is working on internal stuff to get access to github admin rights. In the meantime @tuan-hoang1 @chavafg I've just added `master` to the proxy s390 job ghrpb plugin branch whitelist, which means I believe that s390 jobs will only trigger for master branch PRs, and not any stable branch ones. Let me know if that is *not* what we want :-)
http://jenkins.katacontainers.io/job/kata-containers-proxy-s390x-18.04-PR-initrd/configure

**Comment by alicefr** [comment]
thanks @grahamwhaley !

**Comment by jschintag** [comment]
/test

Lets check if this still works

**Comment by jschintag** [comment]
/test-s390x

Lets check if the regexp works.

**Comment by jschintag** [comment]
/test-s390x

Lets see if we now dodge the fastpath

**Comment by grahamwhaley** [comment]
@jschintag - are we done with this now? Maybe time to close it?

**Comment by jschintag** [comment]
@grahamwhaley Since we currently don't have a s390x VM, we aren't really done. But i agree that we could just open a new one when we need it.

**Comment by grahamwhaley** [comment]
@jschintag - just a check in then ... how is the S390x VM CI looking? Up and functional yet?

**Comment by jschintag** [comment]
@grahamwhaley We are still waiting on ubuntu to resolve the bug. But the Cloud-Hoster is moving to a different infrastructure next month. This might resolve the issue. I will keep you updated. Unfortunately, we still don't have a s390x CI though.

**Comment by fidencio** [comment]
I'm closing this one as it won't make to the final 1.13.0 release.  @tuan-hoang1, there are some efforts with s390x CI for kata-cotainers 2.x, please, follow those up there.

**Pull request closed without merging**
