### PR TITLE
github: Remove issue template and use central one

### PR DESCRIPTION
**Pull request by jodh-intel**
Remove the GitHub issue template from this repository. We already have a
central set of templates [1] that are being used so the template in this
repository is redundant.

[1] - https://github.com/kata-containers/.github/tree/master/.github/ISSUE_TEMPLATE/

Fixes: #284.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Review by devimc — APPROVED** [review]
thanks @jodh-intel

**Comment by cmaf** [comment]
@jodh-intel the diff was deleted, is the PR still relevant?

**Comment by jodh-intel** [comment]
Hi @cmaf - yes it is. The file is deleted on this PR as it is technically redundant - since we already have templates in https://github.com/kata-containers/.github/tree/master/.github/ISSUE_TEMPLATE/, GitHub will use those. I've raised this set of PRs to simply "clean up" and avoid potential confusion.

**Review by cmaf — APPROVED** [review]

**Pull request merged**
