### PR TITLE
vendor: Add missing package dependencies

### LINKED ISSUE #53: Fix vendoring
As shown https://github.com/kata-containers/proxy/pull/50#issuecomment-367035800, the proxy has un-vendored dependencies.

### PR DESCRIPTION
**Pull request by jodh-intel**
Update the vendoring to include missing packages the proxy relies on.

Fixes #53.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Hi @sboeuf - could you take a look?

**Comment by grahamwhaley** [comment]
Q. - we don't seem to have the dep [prune] section here in the toml file - is now maybe the time to add it?

**Comment by jodh-intel** [comment]
Good call. `dep` claims to auto-prune by default now, but it doesn't (yet).

I've updated the `dep` config on the newest commit as that was the cleanest way to do it: if I added the options before fixing the vendoring the diff was very confusing as some new files were pulled in and other were deleted (due to the new more aggressive pruning).

**Comment by jodh-intel** [comment]
I managed to unbreak it! :smile:

Presumably, some of these issues are the result of our CI changing over time.

**Comment by jodh-intel** [comment]
ping @bergwolf, @laijs - could you take a look at this please? Until this lands, all PR CI builds will fail.

**Comment by WeiZhang555** [comment]
Great to see GO test files pruned from vendor :smile: 

LGTM

**Comment by jodh-intel** [comment]
That error is coming from the `tests` repo and is unrelated to the changes on this PR afaics.

@chavafg - could you investigate?

**Comment by laijs** [comment]
LGTM

**Comment by chavafg** [comment]
@grahamwhaley, @jodh-intel the CI failed because #56 is still not merged.

**Pull request merged**
