### PR TITLE
# Kata Containers 1.5.0

### PR DESCRIPTION
**Pull request by katacontainersbot**
- CI: add a CODEOWNERS file

3be7e68 CI: add a CODEOWNERS file

### CODE REVIEW

**Comment by jcvenegas** [comment]
LGTM

**Comment by jcvenegas** [comment]
jenkins-ci-Power8-ubuntu-16-04-initrd: is this a known issue ?
```
17:59:39 bash sanity/check_sanity.sh
17:59:39 ERROR: 1 pods left and found at /var/lib/vc/sbs
17:59:39 make: *** [Makefile:43: functional] Error 1
```

**Comment by jcvenegas** [comment]
power-8 keeps failing.
```
14:59:13 ~/workspace/kata-containers-proxy-Power8-16.04-PR-initrd/go/src/github.com/kata-containers/tests
14:59:13 time="2019-01-22T02:29:13+05:30" level=error msg="SMT is not Off. System is not capable of running Kata Containers" arch=ppc64le name=kata-runtime pid=36440 source=runtime
14:59:13 SMT is not Off. System is not capable of running Kata Containers
```

**Comment by jcvenegas** [comment]
@egernst @chavafg @nitkon I think it is not a blocker yet, right? 
https://github.com/kata-containers/ci/issues/100

**Comment by bergwolf** [comment]
I don't think power is a blocker yet since we are not testing it in other repos.

**Comment by nitkon** [comment]
@jcvenegas : Power is not a blocker yet.

**Comment by jodh-intel** [comment]
lgtm

**Pull request merged**
