### PR TITLE
logging: Redirect yamux warnings/errors to logger

### LINKED ISSUE #88: Enable yamux logging
By default yamux logs warnings and error to `stderr`. However, these messages should be redirected to the logger.

### PR DESCRIPTION
**Pull request by jodh-intel**
Capture yamux messages to the logger.

Fixes #88.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
Nice fix (I'd not twigged we could link the yamux with a writer to the log), but CI is not happy:
```
Goroutine 12 (finished) created at:
  github.com/kata-containers/proxy/vendor/github.com/hashicorp/yamux.newSession()
      /tmp/jenkins/workspace/kata-containers-proxy-ubuntu-16-04-PR/go/src/github.com/kata-containers/proxy/vendor/github.com/hashicorp/yamux/session.go:109 +0x72a
  github.com/kata-containers/proxy/vendor/github.com/hashicorp/yamux.Client()
      /tmp/jenkins/workspace/kata-containers-proxy-ubuntu-16-04-PR/go/src/github.com/kata-containers/proxy/vendor/github.com/hashicorp/yamux/mux.go:86 +0xb6
  github.com/kata-containers/proxy.serve()
      /tmp/jenkins/workspace/kata-containers-proxy-ubuntu-16-04-PR/go/src/github.com/kata-containers/proxy/proxy.go:70 +0x1c5
  github.com/kata-containers/proxy.TestProxy()
      /tmp/jenkins/workspace/kata-containers-proxy-ubuntu-16-04-PR/go/src/github.com/kata-containers/proxy/proxy_test.go:196 +0x297
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:777 +0x16d
==================
--- FAIL: TestSignalBacktrace (0.14s)
	testing.go:730: race detected during execution of test
```

**Comment by jodh-intel** [comment]
ugh - that's going to be fun to debug ;)

**Comment by jodh-intel** [comment]
Fixed it!

@bergwolf - ptal.

**Comment by jodh-intel** [comment]
That's distressing - `go test -race` seems to be racy when running these tests - fine locally and under Jenkins, but unreliable under Travis.

**Comment by jodh-intel** [comment]
Effectively blocked on #90 (as that contains a fix for the Travis OSX bash failure).

**Comment by sboeuf** [comment]
@jodh-intel #90 has been merged, please rebase this one !

**Comment by jodh-intel** [comment]
Hi @sboeuf - branch updated.

**Comment by grahamwhaley** [comment]
@egernst - you wish we had a 'trigger phrase' for Jenkins we could use in comments.... well, that is a feature supported in the github plugins we use in Jenkins afaik - we would just have to define it, configure it, and turn it on...

**Comment by jodh-intel** [comment]
Well, there does appear to be a test race here. I can force it on go 1.8 and 1.10 but it's easier to see on go 1.8.

I'm still digging as the main code fires off go routines... that fire off go routines (in multiple parts of the code). And those go routines are unstoppable fwics as they are doing I/O copy.

I'll take another look tomorrow but might need to get @sboeuf / @bergwolf to take a look, being the original authors of the go routine code.

**Comment by jodh-intel** [comment]
Branch updated. The test race still exists though.

@sboeuf, @bergwolf - ptal to see if you can work out how we can solve this one. I don't think you can interrupt I/O copies so we might need to get creative here :)

**Comment by bergwolf** [comment]
@jodh-intel Could you give a pointer to the logs of the race somewhere?

**Comment by jodh-intel** [comment]
Hi @bergwolf - yep, if you look at the travis log...

```
=== RUN   TestHandleSigtermSignalNilConnectionsSuccess
--- PASS: TestHandleSigtermSignalNilConnectionsSuccess (0.00s)
=== RUN   TestLogger
==================
WARNING: DATA RACE
Write at 0x00c42001cbe0 by goroutine 32:
  github.com/kata-containers/proxy.TestLogger()
      /home/travis/gopath/src/github.com/kata-containers/proxy/proxy_test.go:287 +0x15c
  testing.tRunner()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:657 +0x107

Previous read at 0x00c42001cbe0 by goroutine 13:
  github.com/kata-containers/proxy/vendor/github.com/sirupsen/logrus.Entry.log()
      /home/travis/gopath/src/github.com/kata-containers/proxy/vendor/github.com/sirupsen/logrus/entry.go:117 +0x59e
  github.com/kata-containers/proxy/vendor/github.com/sirupsen/logrus.(*Entry).Warn()
      /home/travis/gopath/src/github.com/kata-containers/proxy/vendor/github.com/sirupsen/logrus/entry.go:150 +0x116
  github.com/kata-containers/proxy.yamuxWriter.Write()
      github.com/kata-containers/proxy/_test/_obj_test/proxy.go:56 +0x1c6
  github.com/kata-containers/proxy.(*yamuxWriter).Write()
      <autogenerated>:1 +0x8d
  log.(*Logger).Output()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/log/log.go:168 +0x39d
  log.(*Logger).Printf()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/log/log.go:175 +0x8f
  github.com/kata-containers/proxy/vendor/github.com/hashicorp/yamux.(*Session).send()
      /home/travis/gopath/src/github.com/kata-containers/proxy/vendor/github.com/hashicorp/yamux/session.go:376 +0x2e1

Goroutine 32 (running) created at:
  testing.(*T).Run()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:697 +0x543
  testing.runTests.func1()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:882 +0xaa
  testing.tRunner()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:657 +0x107
  testing.runTests()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:888 +0x4e0
  testing.(*M).Run()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:822 +0x1c3
  main.main()
      github.com/kata-containers/proxy/_test/_testmain.go:118 +0x33d

Goroutine 13 (finished) created at:
  github.com/kata-containers/proxy/vendor/github.com/hashicorp/yamux.newSession()
      /home/travis/gopath/src/github.com/kata-containers/proxy/vendor/github.com/hashicorp/yamux/session.go:109 +0x7d2
  github.com/kata-containers/proxy/vendor/github.com/hashicorp/yamux.Client()
      /home/travis/gopath/src/github.com/kata-containers/proxy/vendor/github.com/hashicorp/yamux/mux.go:86 +0xb6
  github.com/kata-containers/proxy.serve()
      github.com/kata-containers/proxy/_test/_obj_test/proxy.go:92 +0x20d
  github.com/kata-containers/proxy.TestProxy()
      /home/travis/gopath/src/github.com/kata-containers/proxy/proxy_test.go:199 +0x2c8
  testing.tRunner()
      /home/travis/.gimme/versions/go1.8.linux.amd64/src/testing/testing.go:657 +0x107
==================
--- FAIL: TestLogger (0.00s)
	<autogenerated>:12: 
                          
	Error Trace:	proxy_test.go:294
		
	Error:      	Should be true
		
	Test:       	TestLogger
	<autogenerated>:12: 
                          
	Error Trace:	proxy_test.go:295
		
	Error:      	Should be true
		
	Test:       	TestLogger
	<autogenerated>:12: 
                          
	Error Trace:	proxy_test.go:296
		
	Error:      	Should be true
		
	Test:       	TestLogger
	<autogenerated>:12: 
                          
	Error Trace:	proxy_test.go:300
		
	Error:      	Expected value not to be nil.
		
	Test:       	TestLogger
	testing.go:610: race detected during execution of test
```

**Comment by bergwolf** [comment]
@jodh-intel I think the problem is that the yamux session is not closed properly. Please see if #94 fixes the race.

**Comment by jodh-intel** [comment]
Blocked on #94 (I also need to remove the first commit).

**Comment by sboeuf** [comment]
@jodh-intel please rebase now that #94 has been merged :)

**Comment by jodh-intel** [comment]
Reworked now that #94 has landed.

Ping @kata-containers/proxy.

**Comment by grahamwhaley** [comment]
OK, I think we are in the same 'the CIs that failed do not matter' situation here:
- travis, failed the `yq` on OSX, but passed the others
- codecov - @jodh-intel , are you bothered about the -0.49% diff?
- ARM CI is not functional yet

None of the failing CIs is 'required', so I can press the big `GREY` button if we agree....

**Comment by sboeuf** [comment]
@grahamwhaley yes I agree this can be merged.

**Pull request merged**
