### PR TITLE
logger: Use nanosecond timestamps

### LINKED ISSUE #49: Log using nanosecond timestamps
Currently, the proxy creates log entries with time fields like this:

```
time="2018-02-20T16:18:46Z"
```
... whereas we really want:

```
time="2018-02-20T16:18:46.874088215Z"
```

### PR DESCRIPTION
**Pull request by jodh-intel**
Switch from second resolution to nanosecond resolution log entries.

Fixes #49.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
A bunch of stuff from Travis?
```
proxy_test.go:23:2:warning: unused struct field could not import github.com/stretchr/testify/assert (cannot find package "github.com/stretchr/testify/assert" in any of: (structcheck)
proxy_test.go:233:2:warning: unused struct field undeclared name: assert (structcheck)
proxy_test.go:240:2:warning: unused struct field undeclared name: assert (structcheck)
proxy_test.go:248:2:warning: unused struct field undeclared name: assert (structcheck)
proxy_test.go:255:2:warning: unused struct field undeclared name: assert (structcheck)
```

**Comment by jodh-intel** [comment]
That error seems unrelated to my change. It looks like someone forgot to vendor testify...

I'll raise a PR to correct that...

**Comment by jodh-intel** [comment]
https://github.com/kata-containers/proxy/pull/54 raised, so this PR is blocked on that.

**Comment by laijs** [comment]
LGTM

**Comment by jodh-intel** [comment]
Rebased to keep the CI happy ;)

**Comment by jodh-intel** [comment]
ping @kata-containers/proxy.

**Pull request merged**
